name: Deploy My_Blog  #自动化的名称

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push: # push的时候触发
    branches: [ main ]  # 哪些分支需要触发
  pull_request:  
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Blog_CI-CD:
    runs-on: ubuntu-latest  # 服务器环境
    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
      # 检查代码
      - name: Checkout
        uses: actions/checkout@v2  #软件市场的名称
        with: # 参数
          submodules: true
          persist-credentials: false
          
      - name: Setup Node.js
       # 设置 node.js 环境
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          
      - name: Cache node modules
      # 设置包缓存目录，避免每次下载
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      # 配置Hexo环境 
      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
        run: |
          npm install hexo-cli -g
          npm install
           
      
      # 生成静态文件
      - name: Build
        run: |
          hexo clean 
          hexo g
        
      # 2、部署到 GitHub Pages
      - name: upload GitHub repository
        env: 
          # Github 仓库
          GITHUB_REPO: github.com/sujit-168/sujit-168.github.io
          # Coding 仓库
          #CODING_REPO: e.coding.net/sujit-168/blogs.git
          # Gitee 仓库
          #GITEE_REPO: gitee.com/sujit-168/sujit-168.gitee.io.git
         # 将编译后的博客文件推送到指定仓库
        run: |
          cd ./public && git init && git add .
          git config user.name "sujit-168"
          git config user.email "su2054552689@gmail.com"
          git add .
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
          git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master
#        git push --force --quiet "https://RoYFbFDSfM:${{ secrets.CODING_TOKEN }}@$CODING_REPO" master:master
#        git push --force --quiet "https://yifanzheng:${{ secrets.GITEE_ACCESS_TOKEN }}@$GITEE_REPO" master:master 
      
      # 将编译后的博客文件推送到指定仓库 
      #- name: Deploy
       # uses: JamesIves/github-pages-deploy-action@releases/v3
        #with:
          # ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         # ACTION_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          #REPOSITORY_NAME: sujie-168/sujie-168.github.io
          #BRANCH: main
          #FOLDER: public
          #注意这里的 public 是仓库根目录下的 public，也就是 npm run build 生成静态资源的路径，比如有的人是 `docs/.vuepress/dist`
#          mkdir -p ~/.ssh/
#          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
#          chmod 700 ~/.ssh
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan github.com >> ~/.ssh/known_hosts
#          git config --global user.email "su2054552689@gmail.com"
#          git config --global user.name "sujit-168"
         

#name: HUGO_CI #自动化的名称
#on:
#   push: # push的时候触发
#    branches: # 那些分支需要触发
#      - master
#jobs:
#  build:
#    runs-on: ubuntu-latest # 镜像市场
#    steps:
#      - name: checkout # 步骤的名称.
#        uses: actions/checkout@v2 #软件市场的名称
#        with: # 参数
#          submodules: true
#      - name: Setup Hugo
#        uses: peaceiris/actions-hugo@v2
#        with:
#         hugo-version: '0.64.1'
#          extended: true
#      - name: Build
#        run: hugo
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v2.5.1
#        env:
#          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#          EXTERNAL_REPOSITORY: redisread/redisread.github.io
#          PUBLISH_BRANCH: master
#          PUBLISH_DIR: ./public

      # - name: Deploy to Huawei # 
      # - name: Modify files permissions
      #   run: |
      #     chmod 777 -R ./public
      # - name: Tester
      #   uses: yeshan333/rsync-deploy-action@main
      #   id: rsync-deploy-action
      #   with:
      #     ssh_login_username: ${{ secrets.SSH_USERNAME }}
      #     remote_server_ip: ${{ secrets.SSH_HOST }}
      #     ssh_port: 22
      #     ssh_private_key: ${{ secrets.HUGO_DEPLOY_KEY }}
      #     source_path: ./public/*
      #     destination_path: /usr/local/nginx/html/hugo
        #   # DEPLOY_KEY: ${{ secrets.HUGO_DEPLOY_KEY }} # 引用配置，SSH私钥
        #   # ARGS: -avz --delete --exclude='CNAME' # rsync参数，排除.pyc文件
        #   SERVER_PORT: "22" # SSH端口
        #   FOLDER: ./public # 要推送的文件夹，路径相对于代码仓库的根目录
        #   SERVER_IP: ${{ secrets.SSH_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
        #   USERNAME: ${{ secrets.SSH_USERNAME }} # 引用配置，服务器登录名
        #   SERVER_DESTINATION: /usr/local/nginx/html/hugo # 部署到目标文件夹
